"""
Django settings for kdnuochoa project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-5@ut1(^#=_=z%mmrbg%lkc&wr#@e&xp5qgpv^*6&0btenn7ux0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app',
    'nested_admin',
    'ckeditor',
    'ckeditor_uploader',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'kdnuochoa.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'app.context_processors.global_data',
            ],
        },
    },
]


JAZZMIN_SETTINGS = {
    "site_title": "Quản trị Ami",
    "site_header": "Hệ thống quản lý",
    "site_brand": "Ami Perfume",

    "icons": {
        "app.SanPham": "fas fa-box",
        "app.BienThe": "fas fa-layer-group",
        "app.ThuocTinh": "fas fa-tags",
        "app.GiaTriThuocTinh": "fas fa-list",
        "app.ThuongHieu": "fas fa-copyright",
        "app.LoaiSanPham": "fas fa-th",
        "app.NhomHuong": "fas fa-leaf",
    },

    # "custom_links": {
    #     "app": [
    #         {
    #             "name": "Quản lý sản phẩm",
    #             "url": "app_sanpham_changelist",
    #             "icon": "fas fa-box",
    #         },
    #     ]
    # },

    # 🔥 CHIA NHÓM Ở SIDEBAR
    "order_with_respect_to": [
        "app.SanPham",
        "app.BienThe",
        "app.BienTheThuocTinh",
        "app.ThuocTinh",
        "app.GiaTriThuocTinh",
        "app.LoaiSanPham",
        "app.NhomHuong",
        "app.ThuongHieu",
    ],

    "navigation_expanded": True,
}

CKEDITOR_UPLOAD_PATH = "uploads/"

WSGI_APPLICATION = 'kdnuochoa.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': 'QL_KDNuocHoa',
        'USER': 'doan2',              # hoặc user SQL của bạn
        'PASSWORD': '1111',      # mật khẩu SQL Server
        'HOST': 'localhost',       # hoặc .\SQLEXPRESS
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
            'unicode_results': True, 
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'vi'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# VNPAY Sandbox
VNPAY_TMN_CODE    = "BRH4CBDX"        # Lấy từ sandbox.vnpayment.vn
VNPAY_HASH_SECRET = "5R0WH1ZTB8I4SHUKCI1BHKLNTC6AAASA"     # Secret key từ VNPAY
VNPAY_URL         = "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
VNPAY_RETURN_URL  = "http://localhost:8000/thanh-toan/vnpay-return/"

# MoMo Sandbox
MOMO_PARTNER_CODE = "MOMO"
MOMO_ACCESS_KEY   = "F8BBA842ECF85"
MOMO_SECRET_KEY   = "K951B6PE1waDMi640xX08PD3vg6EkVlz"
MOMO_ENDPOINT     = "https://test-payment.momo.vn/v2/gateway/api/create"
MOMO_RETURN_URL   = "http://localhost:8000/thanh-toan/momo-return/"
MOMO_NOTIFY_URL   = "http://localhost:8000/api/momo-ipn/"